### ISSUE TITLE
Programmatic usage

### ISSUE THREAD

**Issue by jide** [rkaneko/graphql-concat#176]
Is it possible to use this library programmatically ? I would like to merge 2 queries into one with 2 operations. I tried to scan the codebase but couldn't find where to start.

**Comment by rkaneko** [comment]
@jide 

Thank you for your questions.

You mean you want to merge `operation-a.graphql` and `operation-b.graphql` into `merged-operation.graphql` like the followings?

- `operation-a.graphql`

```graphql
query ReadDataA {
  dataA {
    foo
    bar
  }
}
```

- `operation-b.graphql`

```graphql
query ReadDataB {
  dataB {
    bar
    blah
  }
}
```

- `merged-operation.graphql`

```ts
query ReadMerged {
  dataA {
    foo
    bar
  }
  dataB {
    bar
    blah
  }
}
```

**Comment by rkaneko** [comment]
@jide 

Is this API example useful for you?

https://github.com/rkaneko/graphql-concat/commit/b880a9d5c10327e086442267230fd29b66454d05

**Comment by jide** [comment]
Thank you. That's almost what I'm trying to do, but I would have liked to pass queries as strings instead of globs of files.

**Comment by rkaneko** [comment]
@jide

On the current api, we cannot pass graphql as string.

Could you tell me your concrete use cases in detail?

If you could pass graphql as string, what kind of things do you want to realize?

I'd like to decide whether I should work on your feedback or not in this project after I hear what you are creating in detail.

**Comment by rkaneko** [comment]
I cannot receive reply from reporter in detail, so I closed this issue.

**Comment by jide** [comment]
Sorry, I was on vacation. Anyway, I did implement things differently so I guess it's not worth discussing this anymore since it is not the main goal of this project. Thank you for taking time to answer.
